apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1-23
  template:
    metadata:
      labels:
        app: nginx-1-23
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config-2
