apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-3
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location / {
          return 200 "NGINX Version: 1.25\n";
          default_type text/plain;
        }
      }
    }
