apiVersion: v1
kind: Pod
metadata:
  name: broken-seccomp-pod
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.1
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: "non-existing-profile.json"
