apiVersion: v1
kind: Pod
metadata:
  name: seccomp-app
  namespace: default
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.1
    securityContext:
      seccompProfile:
        type: Localhost
        localhostProfile: "profiles/my-profile.json"
